name: CCC News API CI/CD

on:
  schedule:
    - cron: '*/5 * * * *'  # Exécution toutes les 5 minutes
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        pip install -r requirements.txt

    - name: Run tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        DB_URL: ${{ secrets.DB_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        PASS: ${{ secrets.PASS }}
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      run: |
        python -m pytest

    - name: Run Python Script
      env:
        API_KEY: ${{ secrets.API_KEY }}
        DB_URL: ${{ secrets.DB_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        PASS: ${{ secrets.PASS }}
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      run: |
        python app.py
        echo "Script executed at $(date)"
