name: CCC News API CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        API_KEY: ${{ secrets.API_KEY }}
        DB_URL: ${{ secrets.DB_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        PASS: ${{ secrets.PASS }}
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      run: |
        cd API
        python -m pytest

    - name: Deploy to Production
      env:
        API_KEY: ${{ secrets.API_KEY }}
        DB_URL: ${{ secrets.DB_URL }}
        EMAIL: ${{ secrets.EMAIL }}
        PASS: ${{ secrets.PASS }}
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      run: |
        # Add your deployment commands here
        # For example, if using Heroku:
        # heroku container:login
        # heroku container:push web
        # heroku container:release web
